### ISSUE TITLE
Update Glossary

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/ler-ecosystem-map-v2#57]
T3 has updated their glossary. Most recent version is here: https://docs.google.com/document/d/1GspLQoU201Oy7QpMVL3LaBKwy2do8kSPjmidebAXnxE/edit#heading=h.xfopljqvjnsn

Please review and update any changes. Can also change changethe intro sentence from " the draft glossary in progress " to "the glossary"

**Comment by alexfigtree** [comment]
Addressed by #58, closing this ticket
